CXXFLAGS=-O3 -g -Wall -march=native -std=c++20 -fopenmp

# For debugging:
#CXXFLAGS=-O0 -g -Wall -march=native -std=c++20 -D_GLIBCXX_DEBUG

SOLUTIONS=solve solve2

all: $(SOLUTIONS)

clean:
	rm -f $(SOLUTIONS)

.PHONY: all clean
