#CXXFLAGS=-Wall -Wextra -O3 -march=native -std=c++20 -Wno-sign-compare -DNDEBUG -finline-functions
CXXFLAGS=-Wall -Wextra -Og -march=native -std=c++20 -Wno-sign-compare -g

all: solve

clean:
	rm -f solve
