CXXFLAGS=-O3 -g -Wall -march=native -std=c++20 -DNDEBUG

# For debugging:
#CXXFLAGS=-Og -g -Wall -march=native -std=c++20 -D_GLIBCXX_DEBUG

SOLUTIONS=solve

all: $(SOLUTIONS)

clean:
	rm -f $(SOLUTIONS)

.PHONY: all clean
