CXXFLAGS=-Wall -Wextra -O3 -march=native -std=c++20 -Wno-sign-compare
#CXXFLAGS=-Wall -Wextra -Og -march=native -std=c++20 -Wno-sign-compare -g -D_GLIBCXX_DEBUG

all: solve-dp solve-recursive

clean:
	rm -f solve-dp solve-recursive
